upgpkg: electron6 6.1.12-2: re2 20201101 rebuild
Still had to build with clang 10 because of errors like:

    ../../base/optional.h:346:61: error: no member named 'value' in
    'std::is_constructible<blink::LayoutUnit, const
        base::Optional<blink::LayoutUnit> &>'
              std::is_constructible<T, const Optional<U>&>::value ||
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^


git-svn-id: file:///srv/repos/svn-community/svn@775067 9fca08f4-af9d-4005-b8df-a31f2cc04f65