muffin: make it build again after updates to dependencies
- Some ridiculous -Werror in the guts of gobject-introspection:

meta/common.h:401: Warning: Meta: symbol='POINT_IN_RECT': Unknown namespace for symbol 'POINT_IN_RECT'
meta/display.h:62: Warning: Meta: symbol='item': Unknown namespace for symbol 'item'
meta/util.h:100: Warning: Meta: symbol='N_': Unknown namespace for symbol 'N_'
<unknown>:: Fatal: Meta: warnings configured as fatal

- A libglvnd (probably) update caused wayland compilation errors But, muffin
  doesn't wayland, so this should never be a factor??? Turns out some parts of
  wayland aren't correctly defaulted to off:

cogl-texture-2d.c:432:43: error: ‘EGL_WAYLAND_BUFFER_WL’ undeclared (first use in this function)



git-svn-id: file:///srv/repos/svn-community/svn@531543 9fca08f4-af9d-4005-b8df-a31f2cc04f65