upgpkg: python-fiona 1.8.20-5: fix runtime with Python 3.10
Due to the PyPI sources being compiled with older Cython, we were
getting the following error:

  ImportError: /usr/lib/python3.10/site-packages/fiona/
  ogrext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

git-svn-id: file:///srv/repos/svn-community/svn@1065590 9fca08f4-af9d-4005-b8df-a31f2cc04f65