Rename ldap_connect to fix conflict with openldap
In file included from ldap_connect.c:38:
ldap_connect.h:46:12: error: conflicting types for ‘ldap_connect’; have ‘int(char *, struct ld_conn *)’
   46 | extern int ldap_connect(char* _ld_name, struct ld_conn* conn);
      |            ^~~~~~~~~~~~
In file included from ldap_connect.c:35:
/usr/include/ldap.h:1555:1: note: previous declaration of ‘ldap_connect’ with type ‘int(LDAP *)’ {aka ‘int(struct ldap *)’}
 1555 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~


git-svn-id: file:///srv/repos/svn-community/svn@1046148 9fca08f4-af9d-4005-b8df-a31f2cc04f65