Remove ensure_python(">=3.6") call
Traceback (most recent call last):
  File "/build/jupyterlab-widgets/src/jupyterlab_widgets-1.0.2/setup.py", line 18, in <module>
    ensure_python(">=3.6")
  File "/usr/lib/python3.10/site-packages/deprecation.py", line 260, in _inner
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 469, in ensure_python
    raise RuntimeError("ensure_python is deprecated and not compatible with Python 3.10+")
RuntimeError: ensure_python is deprecated and not compatible with Python 3.10+

git-svn-id: file:///srv/repos/svn-community/svn@1064844 9fca08f4-af9d-4005-b8df-a31f2cc04f65