Add three -Wno-error= flags when building perf
Perl 5.36 triggers these warnings which are then treated as errors:

/usr/lib/perl5/5.36/core_perl/CORE/inline.h: In function ‘Perl_is_utf8_valid_partial_char_flags’:
/usr/lib/perl5/5.36/core_perl/CORE/handy.h:125:23: error: cast from function call of type ‘STRLEN’ {aka ‘long unsigned int’} to non-matching type ‘_Bool’ [-Werror=bad-function-cast]
  125 | #define cBOOL(cbool) ((bool) (cbool))
      |                       ^
/usr/lib/perl5/5.36/core_perl/CORE/inline.h:2363:12: note: in expansion of macro ‘cBOOL’
 2363 |     return cBOOL(is_utf8_char_helper_(s0, e, flags));
      |            ^~~~~
In file included from /usr/lib/perl5/5.36/core_perl/CORE/perl.h:7242:
/usr/lib/perl5/5.36/core_perl/CORE/inline.h: In function ‘Perl_cop_file_avn’:
/usr/lib/perl5/5.36/core_perl/CORE/inline.h:3489:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 3489 |     const char *file = CopFILE(cop);
      |     ^~~~~
In file included from /usr/lib/perl5/5.36/core_perl/CORE/perl.h:7243:
/usr/lib/perl5/5.36/core_perl/CORE/sv_inline.h: In function ‘Perl_newSV_type’:
/usr/lib/perl5/5.36/core_perl/CORE/sv_inline.h:376:5: error: enumeration value ‘SVt_LAST’ not handled in switch [-Werror=switch-enum]
  376 |     switch (type) {
      |     ^~~~~~

git-svn-id: file:///srv/repos/svn-community/svn@1216420 9fca08f4-af9d-4005-b8df-a31f2cc04f65