upgpkg: fanficfare 3.27.0-1: upstream release
Now with cloudflare "anti-bot" circumvention because cloudflare is terrible
and fanfiction.net decided to be terrible too.

May not actually work, since my testing "successfully" reported:
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

But apparently it sometimes does work. Who knows. Cloudflare is arbitrary and nuts.


git-svn-id: file:///srv/repos/svn-community/svn@813601 9fca08f4-af9d-4005-b8df-a31f2cc04f65