Bump to 0.31.4
It brings fixes for following compilation error

/usr/include/c++/10.2.0/type_traits:2918:3: error: template with C linkage
 2918 |   template<typename _Result, typename _Fn, typename... _Args>
      |   ^~~~~~~~
In file included from lib/notmuch-private.h:32,
                 from lib/database-private.h:33,
                 from lib/database.cc:21:

git-svn-id: file:///srv/repos/svn-community/svn@895463 9fca08f4-af9d-4005-b8df-a31f2cc04f65