skip failing tests
1. skip tests that require package to already be installed
2. skip test that has a slightly differing error message
```
___________________________ test_stdin_read_warning ____________________________

httpbin = <pytest_httpbin.serve.Server object at 0x7f54add1b520>

    @pytest.mark.requires_external_processes
    @pytest.mark.skipif(is_windows, reason="Windows doesn't support select() calls into files")
    def test_stdin_read_warning(httpbin):
        with stdin_processes(httpbin) as (process_1, process_2):
            # Wait before sending any data
            time.sleep(1)
            process_1.communicate(timeout=0.1, input=b"bleh\n")

            try:
                _, errs = process_2.communicate(timeout=MAX_RESPONSE_WAIT_TIME)
            except subprocess.TimeoutExpired:
                errs = b''

>           assert b'> warning: no stdin data read in 0.1s' in errs
E           assert b'> warning: no stdin data read in 0.1s' in b'Traceback (most recent call last):\n  File "/build/httpie/src/httpie-3.2.1/httpie/__main__.py", line 19, in <module>...pie/__main__.py", line 8, in main\n    from httpie.core import main\nModuleNotFoundError: No module named \'httpie\'\n'

tests/test_uploads.py:157: AssertionError
```

git-svn-id: file:///srv/repos/svn-community/svn@1207776 9fca08f4-af9d-4005-b8df-a31f2cc04f65