upgpkg: flatbuffers 2.0.6-2; backport a fix for tensorflow lite compatibility
Apparently, tensorflow uses flatbuffers 1.x to generate Python codes
from flatbuffers schemes, and it's broken with flatbuffers 2.0.6. For
example, a code snippet from a tensorflow lite tutorial [1] fails with:

Traceback (most recent call last):
  File "/home/yen/tmp/t.py", line 15, in <module>
    tflite_model = converter.convert()
  File "/usr/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 929, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 921, in _convert_and_export_metrics
    return flatbuffer_utils.convert_object_to_bytearray(model_object)
  File "/usr/lib/python3.10/site-packages/tensorflow/lite/tools/flatbuffer_utils.py", line 84, in convert_object_to_bytearray
    model_offset = model_object.Pack(builder)
  File "/usr/lib/python3.10/site-packages/tensorflow/lite/python/schema_py_generated.py", line 5951, in Pack
    operatorCodes = builder.EndVector(len(self.operatorCodes))
TypeError: Builder.EndVector() takes 1 positional argument but 2 were given

(There is another RuntimeError "Mismatching ReplicaContext", which
seems unrelated and harmless.)

As a side note, flatbuffers 2.x compatibility for tensorflow is tracked
in [2].

I've also re-enabled Python tests, which were disabled when switching
to out-of-source builds [3], as well as added a comment for broken C++
tests.

[1] https://www.tensorflow.org/lite/convert#convert_a_keras_model_
[2] https://github.com/tensorflow/tensorflow/issues/51487
[3] https://github.com/archlinux/svntogit-community/commit/b401e47cae6f0f9fb3fa0e75cabd5f55dca6b3b5

git-svn-id: file:///srv/repos/svn-community/svn@1226803 9fca08f4-af9d-4005-b8df-a31f2cc04f65